### ISSUE TITLE
Indirect environment variables

### ISSUE THREAD

**Issue by JonathanKnight** [dmjio/envy#18]
We often use indirect env variables such as 
```
DB_PROVIDER=LOCAL_DB_PROVIDER
LOCAL_DB_PROVIDER=postgres://.....
```
I am trying to read the env variable using something like
```
env <$> env "DB_PROVIDER"
```
but I can't quite get it to work. Any thoughts on this ?

**Comment by dmjio** [comment]
@JonathanKnight I'd try something like this
```haskell
parser :: Var b => Parser b
parser = (env <=< env) "FOO"
```
cheers 🍺
