### ISSUE TITLE
Generics without def config

### ISSUE THREAD

**Issue by creichert** [dmjio/envy#19]
If I have the following data type:

```haskell
data MyEnv = MyEnv {
  envvar1 :: Text
  envvar2 :: Text
} deriving (Generic, FromEnv)
```

I am forced  to write a `DefConfig`. However, I would prefer that if MyEnv can't be loaded from the environment, I just get an error message `Failed to load ENVVAR1...`.

I've tried just setting an error in the `DefConfig` instance, but it always fails. I could make every field `Maybe Text`, but then I would have to handle the errors manually.

Am I missing something?

**Comment by dmjio** [comment]
@creichert, 

This is currently a limitation of envy's `FromEnv` class. Any default instance (i.e. `instance FromEnv SomeType`) must specify a `DefConfig` in the case of failure. We could provide another class which does not have this requirement.

**Comment by creichert** [comment]
Right, I did see that in the source code and it makes sense.

I think there is a use-case for having a generic instance that doesn't require `DefConfig`, and fails when a field is not present. However, this would likely force envy to choose how it would raise the failure, like `(env "ENV_VAR" <|> fail "ENV_VAR not found")`. I'm not sure if this is best-practice or desired.


Do you think a best practice for DefConfig, is to use some kind of "development" defaults, or defer to the defaults of the system the environment variables are intended for? (e.g. postgresql defaults for `PGHOST`, `PGPASSWORD`, etc).

**Comment by dmjio** [comment]
> I think there is a use-case for having a generic instance that doesn't require DefConfig, and fails when a field is not present.

I agree and would like to keep open. In the case you have above, `env "ENV_VAR"` , if missing, `throwError` should be invoked in `ExceptT`. 

https://github.com/dmjio/envy/blob/master/src/System/Envy.hs#L129. 

> I'm not sure if this is best-practice or desired.

Variables should fail in the order they are looked up, and this should also still allow for default arguments to be set via `(.!=)`. It's an impure API, but that's ok.

> Do you think a best practice for DefConfig, is to use some kind of "development" defaults, or defer to the defaults of the system the environment variables are intended for? (e.g. postgresql defaults for PGHOST, PGPASSWORD, etc).

Yea, that would be a good idea. Although I'm not entirely sure how to implement it without making data types for postgresql configuration inside of `envy`.

**Comment by nrolland** [comment]
I actually needed that yesterday, and I have a branch which does it 
https://github.com/nrolland/envy/tree/nodefault

I can send PR (after the other for blank string is in ?)

**Comment by dmjio** [comment]
Sounds great, as long as it’s backwards compatible I’ll merge

**Comment by nrolland** [comment]
what do you think of the blank string stuff ? 

I built on top of it, and it might be easier to merge after you take check that in.

**Comment by jesuspc** [comment]
Any updates on this topic? It would be very useful

**Comment by dmjio** [comment]
@jesuspc seems to be implemented in this PR

https://github.com/dmjio/envy/pull/24

**Comment by dmjio** [comment]
@jesuspc see http://hackage.haskell.org/package/envy

@nrolland I've included your name on the list of authors in the cabal file. Thanks for the contribution (both empty strings and allowing users to not specify `DefConfig`), apologies for how long it took to merge.
