### ISSUE TITLE
Dont't make implementors of FromEnv instance think of the default value

### ISSUE THREAD

**Issue by igrep** [dmjio/envy#34]
As the author of https://github.com/dmjio/envy/issues/19 said, I prefer raising an error when `Parser` fails some way.
So types without default value is not bad.
Why does the `FromEnv` class force the instance to handle the default value?
If a default value is really necessary, just use `fromLeft`:

```haskell
import Data.Either

print =<< (fromLeft defaultConfig <$> decodeEnv :: IO (Either String PGConfig))
```

Thinking of the default is not the responsibility of the instances of `FromEnv`.

**Comment by dmjio** [comment]
@igrep I believe this has been removed (the necessity of specifying a default value), as of https://github.com/dmjio/envy/pull/24

Which version of envy are you on?

**Comment by igrep** [comment]
I mean the first argument of `fromEnv`, added by https://github.com/dmjio/envy/pull/24.

**Comment by dmjio** [comment]
Ah, ok I see.

```haskell
instance FromEnv ConnectInfo where
  fromEnv Nothing = 
    ConnectInfo <$> envMaybe "PG_HOST" .!= "localhost"
		<*> env "PG_PORT"
		<*> env "PG_USER"
		<*> env "PG_PASS"
		<*> env "PG_DB"
        
  fromEnv (Just def) = 
    ConnectInfo <$> envMaybe "PG_HOST" .!= (pgHost def)
		<*> envMaybe "PG_PORT" .!= (pgPort def)
		<*> env "PG_USER" .!= (pgUser def)
		<*> env "PG_PASS" .!= (pgPass def) 
		<*> env "PG_DB" .!= (pgDB def)
```

So what about the case when `PG_HOST` is present, but `PG_PORT` isn't? Ideally we'd like to default to `pgPort` in the record, but use `PG_HOST` from the environment. If we simply fail the entire environment parse after the `PG_PORT` lookup fails, we'd be using `pgHost` from the default record and not from `PG_HOST`. By adding the record inside the parse, we have a hybrid read-from-the-environment-while-default to record behavior.

**Comment by igrep** [comment]
In such a case, we have Higher Kinded Data types (HKDs) as a generalized solution.
Here's an example using the [barbies](https://hackage.haskell.org/package/barbies) package:

```hs
#!/bin/env stack
{-
  stack script
    --resolver=lts-14.22
    --package=envy
    --package=barbies
-}

{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE TemplateHaskell #-}

import GHC.Generics
import Data.Functor.Identity
import Data.Barbie
import System.Envy

data PgConnectInfo f = PgConnectInfo
    { pgHost :: f String
    , pgPort :: f Int
    , pgUser :: f String
    , pgPass :: f String
    , pgDb :: f String
    } deriving
      ( Generic
      , FunctorB, TraversableB, ProductB, ConstraintsB, ProductBC
      )

deriving instance AllBF Show f PgConnectInfo => Show (PgConnectInfo f)
deriving instance AllBF Eq   f PgConnectInfo => Eq   (PgConnectInfo f)

newtype MyMaybe a =
  MyMaybe { unMyMaybe :: Maybe a }

-- Parser without default
parserPgConnectInfo :: Parser (PgConnectInfo Maybe)
parserPgConnectInfo =
  PgConnectInfo
    <$> envMaybe "PG_HOST"
    <*> envMaybe "PG_PORT"
    <*> envMaybe "PG_USER"
    <*> envMaybe "PG_PASS"
    <*> envMaybe "PG_DB"


cInfoDef :: PgConnectInfo Identity
cInfoDef = PgConnectInfo
  { pgHost = Identity "localhost"
  , pgPort = Identity 5432
  , pgUser = Identity "pg"
  , pgPass = Identity "pass"
  , pgDb = Identity "pg"
  }


fill :: ProductB t => t Identity -> t Maybe -> t Identity
fill = bzipWith (\ix -> maybe ix Identity)


main :: IO ()
main = do
  Right cInfo0 <- runEnv parserPgConnectInfo
  let cInfo = fill cInfoDef cInfo0
  print $ cInfo
```

P.S. Late reply due to the flu 😷

**Comment by dmjio** [comment]
@igrep hope you're feeling better :) It's an interesting approach. I'd prefer to keep the default basic, for new users. I don't think the current implementation precludes this approach, so we should be able to have the best of both worlds yea?

**Comment by igrep** [comment]
Okay, I got it.

**Comment by dmjio** [comment]
@igrep I don't deny that `fromEnv _ = Foo <$> fromEnv Nothing <*> fromEnv Nothing` is kind of annoying to write :/ the typeclass approach was nice, but it /forced/ us to use a default even when we didn't want to. Verbosity at the cost of flexibility.
