### ISSUE TITLE
instances for tuples

### ISSUE THREAD

**Issue by endgame** [dmjio/envy#38]
It could be nice to provide FromEnv/ToEnv instances for tuples, including the empty tuple. This would allow users the ability to assemble their environment out of discrete parts.

**Comment by dmjio** [comment]
Sounds good. I'd accept that if you made a PR.

**Comment by endgame** [comment]
I feel like this shouldn't be hard, but the additional `Maybe a` in the argument to `fromEnv` and the phantom type parameter in the return value of `toEnv` make this fiddlier than I first expected. I solved my immediate problem in another way, so I'll leave this issue open in case someone else wants to take a stab.

**Comment by dmjio** [comment]
@endgame mind pasting what you have so far?

**Comment by endgame** [comment]
Sorry, I nuked my local clone when I felt I wasn't making headway.
