### ISSUE TITLE
Constraints on base are incorrect for 2.0 and 2.1

### ISSUE THREAD

**Issue by IamfromSpace** [dmjio/envy#41]
Envy uses `System.Environment.Blank`, but this was not introduced until base-4.11.  This means that when building with older versions of GHC and Cabal, the constraint solver will succeed and select 2.1 as compatible, but fail to build.  It would be better if instead the constraint solver would instead select an older version (assuming it was compatible with the user's needs) or simply failed to solve at all, so that the user would know the next appropriate step.

I'll put up a pull request shortly, but this also needs a revision in Hackage to work correctly.

**Comment by IamfromSpace** [comment]
Thank you for the quick merge on the PR!

If it helps, I can request a hackage revision, as it seems to be [an obvious case](https://github.com/haskell-infra/hackage-trustees/blob/master/policy.md#1-metadata-only-changes-tightening-constraints) for trustee help.  I just didn't want to kick anything like that off before conferring first :)

**Comment by dmjio** [comment]
@IamfromSpace sure, not against that. Wouldn't it be easier for me to just release a minor version bump though?

**Comment by IamfromSpace** [comment]
It should be possible to adjust constraints even without a new release, which is probably the easiest route.  When logged into hackage (via user accounts button in the top corner), the “edit package information” link lets you see and edit each versions cabal file at the bottom of the page.

Minor bump would do the trick too, but I can’t remember how that propagates through Stackage, whereas I know a revision would be immediate.
