### ISSUE TITLE
Relax dependency on bytestring

### ISSUE THREAD

**Issue by magthe** [dmjio/envy#48]
The dependency on `bytestring` (<0.11) prevents the latest release to build with GHC 9.2.4. It appears that a simple adjustment of the dependency would be enough.

(Maybe this is something that could be made quickly by just revising on Hackage, I see @endgame has made such changes in the past.)

**Comment by endgame** [comment]
If you make a PR and it doesn't get attention, then open an issue at https://github.com/haskell-infra/hackage-trustees and a trustee can do the revision. But it's better to go through the package maintainer first.

**Comment by magthe** [comment]
Ah! Thanks, @endgame , I was clicking around Hackage but didn't find that information.

**Comment by ysangkok** [comment]
Didn't see this PR, so I made #50, which also bumps text. Sorry about that.

**Comment by dmjio** [comment]
#50

**Comment by dmjio** [comment]
https://hackage.haskell.org/package/envy-2.1.1.0
