### ISSUE TITLE
Race conditions in testing environmental variables

### ISSUE THREAD

**Issue by mookerji** [dmjio/envy#6]
We found a race condition error while trying to write environmental unit/property tests. Does this come up with Envy's Quickcheck tests? This is likely more of a problem underlying `System.Environment`, but I'm wondering if there's a way to deal with it within Envy. Here's an example definition:

``` haskell
module Types where

import BasicPrelude
import System.Envy

data Conf = Conf
  { _cConfFile      :: Maybe String   
  , _cPort          :: Maybe Word32   
  , _cTimeout       :: Maybe Word32
  } deriving ( Eq, Show )

instance FromEnv Conf where
  fromEnv =
    Conf                  <$>
      envMaybe "CONFFILE" <*>
      envMaybe "PORT"     <*>
      envMaybe "TIMEOUT" 

instance ToEnv Conf where
  toEnv Conf{..} =
    makeEnv [ "CONFFILE" .= _cConfFile
            , "PORT"     .= _cPort
            , "TIMEOUT"  .= _cTimeout
            ]

```

and an example test...

``` haskell
module Test
  ( tests
  ) where

import BasicPrelude
import Data.Text
import System.Environment
import System.Envy
import Test.Tasty
import Test.Tasty.HUnit

testEnv :: TestTree
testEnv =
  testGroup "Environmental configuration unit test"
    [ testCase "Empty configuration" $ do
        unsetEnv "SKYLARK_CONFFILE"
        unsetEnv "SKYLARK_PORT"
        unsetEnv "SKYLARK_TIMEOUT"
        c <- decodeEnv :: IO (Either String Conf)
        c @?= Right Conf { _cConfFile = Nothing
                         , _cPort = Nothing
                         , _cTimeout = Nothing
                         }
    , testCase "Port and Timeout" $ do
        unsetEnv "SKYLARK_CONFFILE"
        setEnv "SKYLARK_PORT" "1"
        setEnv "SKYLARK_TIMEOUT" "1"
        c <- decodeEnv :: IO (Either String Conf)
        c @?= Right Conf { _cConfFile = Nothing
                         , _cPort = Just 1
                         , _cTimeout = Just 1
                         }
    ]
```

This test can sometimes pass, or it fail, with the decoded environment in one test case being _not_ the one set in that specific test case. For example, the first case unsetting the environmental variables can instead read the values set in the second test case. This also appears with a Quickcheck not too different from the one committed with Envy (https://gist.github.com/mookerji/d6c9fe48bc35e16bd5690).

**Comment by dmjio** [comment]
@mookerji are you running the tests concurrently per chance?

**Comment by codygman** [comment]
For something similar I've been recommended "compile with -threaded" though
don't know why.

**Comment by mookerji** [comment]
@dmjio Indeed! I thought that I had removed the threaded flags (I know) and had it still fail, but I must have hallucinated. Removing that flag indeed fixed the problem (see: https://github.com/swift-nav/skylark-core/pull/15/files).

That being said, in a more abstract sense, I feel like you'd want still want some notion of thread safety when calling out for environmental variables?

**Comment by dmjio** [comment]
@mookerji for setting them, possibly, if what you're doing isn't simple. But that should be up to the user IMO.
